### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by Hipapheralkus** [PortSwigger/backslash-powered-scanner#11]
Hi,
I have an Active Scan running on a single thread; Thorough speed, Minimize false negative, Use intelligent attack selection. I have most of the Active scan areas checked, I'm using Burp v1.7.27 Pro on Windows Server 2012 R2, 64-bit Java 1.8.0_112-b15 and Backslash powered scanner v0.91. I can see following exception in the Errors tab in Extender:
```
java.lang.NullPointerException
	at burp.OfferParamGuess.createMenuItems(BurpExtender.java:364)
	at burp.ohd.a(Unknown Source)
	at burp.cwd.a(Unknown Source)
	at burp.to.b(Unknown Source)
	at burp.to.a(Unknown Source)
	at burp.q7b.b(Unknown Source)
	at burp.q7b.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
I'm unsure if it causes any problems, or what further information should I provide you, but I just thought I will share what I can to improve this awesome tool:)

**Comment by albinowax** [comment]
Thanks for the report, I've commited a fix for this and it'll come out on the next update. For now I'd just ignore it; it simply means the tool didn't display a context menu option when it didn't make sense anyway.
