### ISSUE TITLE
throwing error/ not working

### ISSUE THREAD

**Issue by dorkerdevil** [PortSwigger/backslash-powered-scanner#18]
java.lang.UnsupportedClassVersionError: burp/BurpExtender has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at burp.ab2.a(Unknown Source)
	at burp.ab2.<init>(Unknown Source)
	at burp.cg9.a(Unknown Source)
	at burp.exv.lambda$panelLoaded$0(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
The extension could not be loaded because it requires a later version of Java. To use this extension you will need to start Burp with the required or later Java version.

**Comment by albinowax** [comment]
Sounds like you're on old Java. Try updating Java, or using the platform installer for Burp

**Comment by dorkerdevil** [comment]
my java is in the newest version

**Comment by dorkerdevil** [comment]
i think i have to lower down the version probably, will update

**Comment by ricardojba** [comment]
Same issue here. Running JRE 8 update 221 on Windows 10 x64 (1803) which is the latest available for download.

**Comment by albinowax** [comment]
Java 8 is beyond end of life. I'll look into removing this dependency if it's straightforward but you need to use Java 11+, or Burp's platform installer.
