### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by nancheal** [PortSwigger/backslash-powered-scanner#21]
Backslash powered scanner extender errors page says:
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 0
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at burp.DiffingScan.findReflectionIssues(DiffingScan.java:431)
	at burp.FastScan.doActiveScan(BurpExtender.java:105)
	at burp.gj2.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
is there any bug?

**Comment by albinowax** [comment]
Thanks, fixed: https://github.com/PortSwigger/backslash-powered-scanner/commit/1f52acb90179c38042444be879a3e99968751387
