### ISSUE TITLE
Cannot Import Local Build of Extension

### ISSUE THREAD

**Issue by decidedlygray** [PortSwigger/backslash-powered-scanner#4]
(This may be a duplicate of #3, but that user did not leave many details. If these issues end up being the same feel free to close.)

### Issue: Current repository cannot be imported to Burp because of a missing resource

Currently, in Utilities.java, line 40 references a resource that is not currently committed to the repository. The resource is named `/functions`. Code, starting at the bad reference on line 40:

```
        Scanner s = new Scanner(getClass().getResourceAsStream("/functions"));
        while (s.hasNext()) {
            phpFunctions.add(s.next());
        }
```
The result is the Java code compiles, the jar can be built, but when you actually import into Burp you get this error message:

```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:72)
	at java.util.Scanner.<init>(Scanner.java:563)
	at burp.Utilities.<init>(Utilities.java:40)
	at burp.BurpExtender.registerExtenderCallbacks(BurpExtender.java:16)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at burp.nie.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)
```

### Temporary workaround

In case others are interested, a workaround is to just copy the missing resource from the existing jar from the BApp store and place it in the proper location when building the jar. After doing that I've been able to successfully build the extension and import it into Burp Pro.

I've also created a fork that contains the missing resource and provides a PowerShell build script. Happy to submit a PR if you want to integrate, but this should be enough for now to help people get their local modifications up and running.

**Comment by albinowax** [comment]
I've added the functions wordlist: https://github.com/PortSwigger/backslash-powered-scanner/commit/8bce9c9ac7cba8bd3d9683a47ba1b138e93e1727

Feel free to submit a pull request with the powershell build script. I'll kill off the apache-commons dependency pretty soon.
